"""
GuardReport: Data structures for safety scan reports

This module defines the GuardReport dataclass which encapsulates the results
of a safety scan performed by the Guard class.
"""

from dataclasses import dataclass, field


@dataclass
class GuardReport:
    """
    Report generated by Guard.scan() containing safety analysis results.

    This dataclass captures comprehensive information about a prompt's safety
    status, including risk scoring, PII detection, prompt injection detection,
    and any detected issues.

    Attributes:
        prompt: The original prompt that was scanned
        risk_score: Float between 0.0 and 1.0 indicating overall risk level
                   (0.0 = safe, 1.0 = highest risk)
        pii_detected: Boolean indicating if Personally Identifiable Information
                     was detected in the prompt
        injection_detected: Boolean indicating if a prompt injection attack
                          was detected
        issues: List of strings describing specific issues found during the scan
    """

    prompt: str
    risk_score: float = 0.0
    pii_detected: bool = False
    injection_detected: bool = False
    issues: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        """
        Validate GuardReport data after initialization.

        Raises:
            ValueError: If risk_score is not between 0.0 and 1.0
        """
        if not 0.0 <= self.risk_score <= 1.0:
            raise ValueError(
                f"risk_score must be between 0.0 and 1.0, got {self.risk_score}"
            )

    def __str__(self) -> str:
        """
        Generate a formatted safety report string.

        Returns:
            Formatted string representation of the safety report
        """
        issues_str = "\n  - ".join(self.issues) if self.issues else "None"
        if issues_str != "None":
            issues_str = "\n  - " + issues_str

        return f"""## GuardLLM Safety Report

Prompt: {self.prompt}
Risk Score: {self.risk_score}
PII Detected: {self.pii_detected}
Prompt Injection Detected: {self.injection_detected}
Issues: {issues_str}"""
